spring.application.name=dss
spring.profiles.active=dev
spring.data.mongodb.uri=mongodb://13.60.180.184:27017/dbtrack


spring.data.mongodb.connectTimeout=1800
spring.data.mongodb.readTimeout=1000
spring.data.mongodb.maxWaitTime=10
spring.data.mongodb.maxConnectionIdleTime=10
spring.data.mongodb.maxConnecting=200
spring.data.mongodb.minSize= 0
spring.data.mongodb.maxSize= 1000


# Redis host dan port (default localhost & 6379)
spring.data.redis.host=16.171.15.62
spring.data.redis.port=6379

# (Opsional) Kalau Redis pakai password
# spring.redis.password=yourStrongPassword

# (Opsional) Timeout connection (default: 60s)
spring.data.redis.timeout=60000

# (Opsional) Gunakan database index (0-15, default 0)
# spring.redis.database=0

spring.r2dbc.password=qwerty
spring.r2dbc.username=postgres
spring.r2dbc.url=r2dbc:postgresql://16.171.133.243:5432/postgres


spring.kafka.bootstrap-servers=13.49.74.184:9092
receiver.group-id=dss-1
receiver.client-id=dss-proxmox-1
dss.receiver.topic=api-dss


